import 'dart:io';

import 'package:heif_converter/heif_converter.dart';
import 'package:image/image.dart' as img;
import 'package:logger/logger.dart';
import 'package:path/path.dart' as p;

import '../models/export_job.dart';
import '../utils/format_utils.dart';
import '../utils/isolate_utils.dart';

class ConversionException implements Exception {
  ConversionException(this.message);

  final String message;

  @override
  String toString() => message;
}

class PdfInputImage {
  const PdfInputImage({required this.path, required this.isTemporary});

  final String path;
  final bool isTemporary;
}

class ConversionService {
  ConversionService(this._logger);

  final Logger _logger;

  Future<String> convertToImage({
    required String sourcePath,
    required String outputPath,
    required ExportTargetFormat targetFormat,
    required int quality,
  }) async {
    if (targetFormat == ExportTargetFormat.pdf) {
      throw ConversionException(
        'PDF is generated by the PDF service, not image conversion.',
      );
    }

    final sourceExt = extensionFromPath(sourcePath);
    final outputFormat = exportFormatExtension(targetFormat);

    try {
      if (sourceExt == 'heic' || sourceExt == 'heif') {
        final converted = await HeifConverter.convert(
          sourcePath,
          output: outputPath,
          format: outputFormat,
        );
        if (converted == null || !File(converted).existsSync()) {
          throw ConversionException('Could not convert this HEIC/HEIF file.');
        }
        return converted;
      }

      final shouldCopyDirectly =
          (targetFormat == ExportTargetFormat.png && sourceExt == 'png') ||
          (targetFormat == ExportTargetFormat.jpg &&
              (sourceExt == 'jpg' || sourceExt == 'jpeg') &&
              quality >= 99);

      if (shouldCopyDirectly) {
        await File(sourcePath).copy(outputPath);
        return outputPath;
      }

      await runInBackground(() {
        _transcodeImageSync(
          sourcePath: sourcePath,
          outputPath: outputPath,
          format: outputFormat,
          quality: quality,
        );
      });
      return outputPath;
    } catch (error, stackTrace) {
      _logger.e(
        'Image conversion failed',
        error: error,
        stackTrace: stackTrace,
      );
      if (error is ConversionException) {
        rethrow;
      }
      throw ConversionException(
        'Conversion failed for ${p.basename(sourcePath)}.',
      );
    }
  }

  Future<PdfInputImage> prepareForPdf({
    required String sourcePath,
    required String workingDirectory,
  }) async {
    final ext = extensionFromPath(sourcePath);
    if (ext == 'heic' || ext == 'heif') {
      final outputPath = p.join(
        workingDirectory,
        '${p.basenameWithoutExtension(sourcePath)}_${DateTime.now().millisecondsSinceEpoch}.jpg',
      );
      final converted = await HeifConverter.convert(
        sourcePath,
        output: outputPath,
        format: 'jpg',
      );
      if (converted == null || !File(converted).existsSync()) {
        throw ConversionException(
          'Could not prepare HEIC/HEIF file for PDF conversion.',
        );
      }
      return PdfInputImage(path: converted, isTemporary: true);
    }

    if (ext == 'jpg' || ext == 'jpeg' || ext == 'png') {
      return PdfInputImage(path: sourcePath, isTemporary: false);
    }

    throw ConversionException('Unsupported format for PDF export: .$ext');
  }
}

void _transcodeImageSync({
  required String sourcePath,
  required String outputPath,
  required String format,
  required int quality,
}) {
  final bytes = File(sourcePath).readAsBytesSync();
  final decoded = img.decodeImage(bytes);
  if (decoded == null) {
    throw ConversionException('Could not decode image bytes.');
  }

  late final List<int> encoded;
  if (format == 'png') {
    encoded = img.encodePng(decoded);
  } else {
    encoded = img.encodeJpg(decoded, quality: quality);
  }

  File(outputPath)
    ..createSync(recursive: true)
    ..writeAsBytesSync(encoded, flush: true);
}
